name: Deploy Release

run-name: Deploy | ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract region
        run: |
          TAG="${GITHUB_REF_NAME}"
          REGION="${TAG##*-}"
          echo "Deploying $TAG to $REGION"
