name: Deploy

run-name: Deploy ${{ inputs.tag }} to ${{ inputs.aws_region }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag (example: v1.0.0)
        required: true
      aws_region:
        description: AWS region (example: us-east-1)
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print values
        run: |
          echo "Tag: ${{ inputs.tag }}"
          echo "Region: ${{ inputs.aws_region }}"
