name: Deploy Release

run-name: Deploy -> ${{ github.ref_name && github.ref_name.split('-')[1] }} -> ${{ github.ref_name.split('-')[0] }}

on:
  push:
    tags:
      - 'v*-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"
